server:
  port: 8080  # 配置端口号
  servlet:
    context-path: /kuang  # 配置项目路径

spring:
  messages:
    basename: i18n.login  # 配置文件的真实位置
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root


logging:
  level:
    com.kuangshen.mapper: debug   # 输出SQL日志